# Generated by Django 4.1.6 on 2023-04-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_profile_created_delivery_profile_moderated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_profile',
            name='driver_license',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
