# Generated by Django 4.1.6 on 2023-04-13 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_payment_method_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0003_delivery_profile_driver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deliverer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order'),
        ),
    ]
