# Generated by Django 4.1.6 on 2023-04-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_remove_location_street_name'),
        ('delivery', '0004_alter_delivery_deliverer_alter_delivery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='start_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AddField(
            model_name='delivery_point',
            name='priority',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='delivery_point',
            unique_together={('priority', 'location')},
        ),
    ]
