# Generated by Django 4.1.6 on 2023-04-20 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_remove_location_street_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0006_alter_delivery_point_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('moderated', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.delivery_profile_status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery_Profile',
        ),
    ]
