# Generated by Django 4.1.6 on 2023-04-20 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliverer_profile_delete_delivery_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery_Profile_Status',
            new_name='Deliverer_Profile_Status',
        ),
    ]
