# Generated by Django 4.1.6 on 2023-04-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_rename_delivery_profile_status_deliverer_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverer_profile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
