# Generated by Django 4.1.6 on 2023-04-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_delivery_total_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='delivery.deliverer_profile'),
        ),
        migrations.AlterField(
            model_name='delivery_point',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='delivery.deliverer_profile'),
        ),
    ]
