# Generated by Django 4.1.6 on 2023-04-23 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_delivery_deliverer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_point',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='delivery.delivery'),
        ),
    ]
