# Generated by Django 4.1.6 on 2023-04-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_delivery_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverer_profile',
            old_name='last_active',
            new_name='end_time',
        ),
    ]
