# Generated by Django 4.1.6 on 2023-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_rename_last_active_deliverer_profile_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverer_profile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
