# Generated by Django 4.1.6 on 2023-04-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_deliverer_profile_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverer_profile',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
