# Generated by Django 4.1.6 on 2023-04-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_deliverer_profile_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverer_profile',
            options={'verbose_name': 'Deliverer_Profile'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Deliverery'},
        ),
        migrations.AlterModelTable(
            name='deliverer_profile',
            table='Deliverer_Profile',
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='Deliverery',
        ),
    ]
