# Generated by Django 4.1.6 on 2023-04-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_alter_deliverer_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='arrived',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
