# Generated by Django 4.1.6 on 2023-03-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_location_profile_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='locations',
        ),
    ]
