# Generated by Django 4.1.6 on 2023-03-29 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_location_description_remove_location_latitude_and_more'),
        ('profiles', '0005_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
    ]
