# Generated by Django 4.1.6 on 2023-03-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
