# Generated by Django 4.1.6 on 2023-03-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_gender_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='Gender',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profiles',
        ),
        migrations.AlterModelTable(
            name='user_status',
            table='User_Status',
        ),
    ]
