# Generated by Django 4.1.6 on 2023-04-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_profile_citizen_identity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='citizen_identity',
            new_name='citizen_identity_card',
        ),
    ]
