# Generated by Django 4.1.6 on 2023-04-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_product_price_order_product_price_currency'),
        ('profiles', '0022_rename_citizen_identity_profile_citizen_identity_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
