# Generated by Django 4.1.6 on 2023-05-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_complaint',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='product_complaint',
            name='product',
        ),
        migrations.RemoveField(
            model_name='store_complaint',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='store_complaint',
            name='store',
        ),
        migrations.AddField(
            model_name='complaint',
            name='targer_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='target_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Order_Complaint',
        ),
        migrations.DeleteModel(
            name='Product_Complaint',
        ),
        migrations.DeleteModel(
            name='Store_Complaint',
        ),
    ]
