# Generated by Django 4.1.6 on 2023-05-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderating', '0004_moderator_changelog_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderator_changelog',
            old_name='targer_type',
            new_name='target_type',
        ),
    ]
