# Generated by Django 4.1.6 on 2023-02-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
