# Generated by Django 4.1.6 on 2023-03-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longtitude',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.TextField(default=''),
        ),
    ]
