# Generated by Django 4.1.6 on 2023-03-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_country_alter_location_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='Country',
        ),
        migrations.AlterModelTable(
            name='location',
            table='Location',
        ),
    ]
