# Generated by Django 4.1.6 on 2023-04-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_country_table_alter_location_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location'},
        ),
    ]
