# Generated by Django 4.1.6 on 2023-04-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_country_options_alter_location_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='postal_code',
        ),
    ]
