# Generated by Django 4.1.6 on 2023-04-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_remove_location_country_location_lat_location_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city',
            new_name='region',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='street_name',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='subregion_1',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='subregion_2',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=16.07387),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=108.14975),
        ),
    ]
