# Generated by Django 4.1.6 on 2023-04-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_rename_city_location_region_location_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_name',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='subregion_1',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='subregion_2',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
