# Generated by Django 4.1.6 on 2023-04-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_alter_location_address_alter_location_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='street_name',
        ),
    ]
