# Generated by Django 4.1.6 on 2023-03-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_review',
            old_name='products',
            new_name='store',
        ),
    ]
