# Generated by Django 4.1.6 on 2023-03-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_rename_products_store_review_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='store_review',
            name='store',
        ),
        migrations.DeleteModel(
            name='Store_Report',
        ),
        migrations.DeleteModel(
            name='Store_Review',
        ),
    ]
