# Generated by Django 4.1.6 on 2023-04-01 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_store_table_alter_store_status_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store'},
        ),
        migrations.AlterModelOptions(
            name='store_status',
            options={'verbose_name': 'Store_Status'},
        ),
        migrations.AddField(
            model_name='store',
            name='close_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store_status'),
        ),
    ]
