# Generated by Django 4.1.6 on 2023-04-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_alter_store_options_alter_store_status_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
