# Generated by Django 4.1.6 on 2023-04-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='avatar',
            field=models.ImageField(default='stores/store.png', upload_to='stores/'),
        ),
    ]
