# Generated by Django 4.1.6 on 2023-04-05 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_rename_name_store_status_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='close_hour',
        ),
        migrations.RemoveField(
            model_name='store',
            name='open_hour',
        ),
        migrations.CreateModel(
            name='Store_Opening_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.opening_hours')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'opening_hours')},
            },
        ),
    ]
