# Generated by Django 4.1.6 on 2023-04-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_opening_hours_remove_store_close_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='locations',
            new_name='location',
        ),
    ]
