# Generated by Django 4.1.6 on 2023-04-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_rename_locations_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
