# Generated by Django 4.1.6 on 2023-04-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_store_opening_hours_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='moderated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Store_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='stores/images/store_image.png', upload_to='stores/images')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.store')),
            ],
        ),
    ]
