# Generated by Django 4.1.6 on 2023-04-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_store_moderated_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='business_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='tax_identification',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
