# Generated by Django 4.1.6 on 2023-02-15 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_images_product_image_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price_currency',
            new_name='total_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='foodmaker',
        ),
        migrations.RemoveField(
            model_name='order',
            name='images',
        ),
        migrations.AlterField(
            model_name='order_product',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.CreateModel(
            name='Order_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='images',
            field=models.ImageField(default='products.png', upload_to='products/'),
        ),
    ]
