# Generated by Django 4.1.6 on 2023-03-01 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_location_description_remove_location_latitude_and_more'),
        ('stores', '0001_initial'),
        ('orders', '0003_alter_order_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliverer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dest_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_location',
        ),
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='stores.store'),
            preserve_default=False,
        ),
    ]
