# Generated by Django 4.1.6 on 2023-03-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
    ]
