# Generated by Django 4.1.6 on 2023-03-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_delivery_status_order_status_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='delivery_status',
            table='Delivery_Status',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='order_log',
            table='Order_Log',
        ),
        migrations.AlterModelTable(
            name='order_product',
            table='Order_Product',
        ),
        migrations.AlterModelTable(
            name='order_review',
            table='Order_Review',
        ),
        migrations.AlterModelTable(
            name='order_status',
            table='Order_Status',
        ),
        migrations.AlterModelTable(
            name='payment_status',
            table='Payment_Status',
        ),
        migrations.AlterModelTable(
            name='product_status',
            table='Order_Product_Status',
        ),
    ]
