# Generated by Django 4.1.6 on 2023-04-01 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_delivery_status_table_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery_status',
            options={'verbose_name': 'Delivery_Status'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='order_log',
            options={'verbose_name': 'Order_Log'},
        ),
        migrations.AlterModelOptions(
            name='order_product',
            options={'verbose_name': 'Order_Product'},
        ),
        migrations.AlterModelOptions(
            name='order_review',
            options={'verbose_name': 'Order_Review'},
        ),
        migrations.AlterModelOptions(
            name='order_status',
            options={'verbose_name': 'Order_Status'},
        ),
        migrations.AlterModelOptions(
            name='payment_status',
            options={'verbose_name': 'Payment_Status'},
        ),
        migrations.AlterModelOptions(
            name='product_status',
            options={'verbose_name': 'Order_Product_Status'},
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.delivery_status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order_status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.payment_status'),
        ),
    ]
