# Generated by Django 4.1.6 on 2023-04-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_delivery_status_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_status',
            old_name='name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='order_status',
            old_name='name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='payment_status',
            old_name='name',
            new_name='code',
        ),
    ]
