# Generated by Django 4.1.6 on 2023-04-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_payment_method_alter_order_shipper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipper',
        ),
    ]
