# Generated by Django 4.1.6 on 2023-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='moderated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
