# Generated by Django 4.1.6 on 2023-04-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_payment_method_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Status',
            new_name='Order_Product_Status',
        ),
    ]
