# Generated by Django 4.1.6 on 2023-04-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_delivery_fee_order_delivery_fee_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_product',
            old_name='price',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='order_product',
            old_name='price_currency',
            new_name='total_currency',
        ),
    ]
