# Generated by Django 4.1.6 on 2023-04-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_product_price_order_product_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='image',
            field=models.ImageField(default='order_products.png', upload_to='order_products/'),
        ),
    ]
