# Generated by Django 4.1.6 on 2023-04-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_product_created_order_product_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='image',
            field=models.ImageField(default='order_products/order_product.png', upload_to='order_products/'),
        ),
    ]
