# Generated by Django 4.1.6 on 2023-04-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_order_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(default='orders/order.png', upload_to='orders'),
        ),
    ]
