# Generated by Django 4.1.6 on 2023-03-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_review',
            old_name='products',
            new_name='product',
        ),
    ]
