# Generated by Django 4.1.6 on 2023-03-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_report',
            name='images',
            field=models.ImageField(null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='product_review',
            name='images',
            field=models.ImageField(null=True, upload_to='reviews/'),
        ),
    ]
