# Generated by Django 4.1.6 on 2023-03-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_status_product_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='product_report',
            table='Product_Report',
        ),
        migrations.AlterModelTable(
            name='product_review',
            table='Product_Review',
        ),
        migrations.AlterModelTable(
            name='product_status',
            table='Product_Status',
        ),
    ]
