# Generated by Django 4.1.6 on 2023-04-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_category_table_alter_product_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='product_report',
            options={'verbose_name': 'Product_Report'},
        ),
        migrations.AlterModelOptions(
            name='product_review',
            options={'verbose_name': 'Product_Review'},
        ),
        migrations.AlterModelOptions(
            name='product_status',
            options={'verbose_name': 'Product_Status'},
        ),
    ]
