# Generated by Django 4.1.6 on 2023-04-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_status',
            old_name='name',
            new_name='code',
        ),
    ]
