# Generated by Django 4.1.6 on 2023-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_name_product_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
